# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sign_in(object):
    def setupUi(self, sign_in):
        sign_in.setObjectName("sign_in")
        sign_in.resize(811, 477)
        self.sign_in_widget = QtWidgets.QWidget(sign_in)
        self.sign_in_widget.setGeometry(QtCore.QRect(10, 10, 781, 441))
        self.sign_in_widget.setObjectName("sign_in_widget")
        self.login_label = QtWidgets.QLabel(self.sign_in_widget)
        self.login_label.setGeometry(QtCore.QRect(490, 50, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.login_label.setFont(font)
        self.login_label.setObjectName("login_label")
        self.label = QtWidgets.QLabel(self.sign_in_widget)
        self.label.setGeometry(QtCore.QRect(410, 190, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.name_label = QtWidgets.QLabel(self.sign_in_widget)
        self.name_label.setGeometry(QtCore.QRect(410, 140, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.password_lineEdit = QtWidgets.QLineEdit(self.sign_in_widget)
        self.password_lineEdit.setGeometry(QtCore.QRect(490, 190, 181, 21))
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.workid_lineEdit = QtWidgets.QLineEdit(self.sign_in_widget)
        self.workid_lineEdit.setGeometry(QtCore.QRect(490, 140, 181, 21))
        self.workid_lineEdit.setObjectName("workid_lineEdit")
        self.login_pushButton = QtWidgets.QPushButton(self.sign_in_widget)
        self.login_pushButton.setGeometry(QtCore.QRect(490, 260, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.login_pushButton.setFont(font)
        self.login_pushButton.setObjectName("login_pushButton")

        self.retranslateUi(sign_in)
        QtCore.QMetaObject.connectSlotsByName(sign_in)

    def retranslateUi(self, sign_in):
        _translate = QtCore.QCoreApplication.translate
        sign_in.setWindowTitle(_translate("sign_in", "Form"))
        self.login_label.setText(_translate("sign_in", "登录"))
        self.label.setText(_translate("sign_in", "密码："))
        self.name_label.setText(_translate("sign_in", "工号："))
        self.login_pushButton.setText(_translate("sign_in", "登录"))
